services:
  nextjs:
    build: ./nextjs
    working_dir: /nextjs/
    volumes:
      - ./nextjs/:/nextjs
      - /nextjs/node_modules
    ports:
      - 80:3000
    networks:
      - net
  sanic:
    build: ./sanic
    volumes:
      - ./sanic/src/:/sanic/src
    ports: 
      - 8000:8000
    networks:
      - net
  openpose:
    profiles:
      - openpose
    build: ./openpose
    volumes:
      - ./openpose/sign-language-recognition-service:/sign-language-regocnition-service
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
networks:
   net:
