services:
  nextjs:
    build: ./nextjs
    working_dir: /nextjs/
    volumes:
      - ./nextjs/:/nextjs
      - /nextjs/node_modules
    ports:
      - 80:3000
  sanic:
    build: ./sanic
    volumes:
      - ./sanic/src/:/sanic/src
    ports: 
      - 8080:8000