services:
  nextjs:
    build: ./nextjs
    working_dir: /nextjs/
    volumes:
      - ./nextjs/:/nextjs
      - /nextjs/node_modules
    ports:
      - 80:3000
    networks:
      - net
  sanic:
    build: ./sanic
    volumes:
      - ./sanic/src/:/sanic/src
    ports: 
      - 8080:8080
    networks:
      - net
  openpose:
    profiles:
      - openpose
    build: ./openpose
    ports:
      - 5000:5000
    volumes:
      - ./openpose/sendVideo.py:/sendvideo/sendVideo.py
      - ./openpose/video/:/sendvideo/video
      - ./openpose/the_test/:/the_test/
    environment:
      - "PYTHONUNBUFFERED=1"
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    networks:
      - net
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
networks:
   net:
